// <auto-generated />
namespace VehicleInspectionReminder.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateidgenerater : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateidgenerater));
        
        string IMigrationMetadata.Id
        {
            get { return "201603210825256_update id generater "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
